---
title: "Reproducible Research: Peer Assessment 1"
author: "JianXun Liu"
date: "March 5, 2016"
output: html_document
---

```{r}
getwd()
setwd("/Users/aliu/Documents/Data_Science_Coursera/RepData_PeerAssessment1")
```

## Loading and preprocessing the data
```{r}
if(!file.exists('activity.csv')){
    unzip('activity.zip')
}
Data <- read.csv('activity.csv')
Data$interval <- strptime(gsub("([0-9]{1,2})([0-9]{2})", "\\1:\\2", Data$interval), format='%H:%M')
```

## What is mean total number of steps taken per day?


```{r}
library(ggplot2)
total.steps <- tapply(data$steps, data$date, FUN=sum, na.rm=TRUE)
mean(total.steps, na.rm=TRUE)
median(total.steps, na.rm=TRUE)
```

```{r, echo=FALSE}
qplot(total.steps, binwidth=1000, xlab="total number of steps taken each day")
```


## What is the average daily activity pattern?

```{r}
averages <- aggregate(x=list(steps=data$steps), by=list(interval=data$interval),
                      FUN=mean, na.rm=TRUE)
```

```{r, echo=FALSE}
ggplot(data=averages, aes(x=interval, y=steps)) +
  geom_line() +
  xlab("5-minute interval") +
  ylab("average number of steps taken")
```

## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
